Repository FilipMadzia/Melodie, pull requests merged in 2024-08, with the labels that each got.

#27 Added ArtistRepository + fixed api context
  Melodie.API/Data/MelodieAPIContext.cs
  Melodie.API/Repositories/ArtistRepository.cs
Labels: bug, feature

#35 Added TrackRepository
  Melodie.API/Repositories/TrackRepository.cs
Labels: feature

#37 Added SingleRepository
  Melodie.API/Repositories/SingleRepository.cs
Labels: feature

#38 Added PlaylistRepository
  Melodie.API/Repositories/PlaylistRepository.cs
Labels: feature

#40 Repositories
  Melodie.API/Data/Entities/UserEntity.cs
  Melodie.API/Data/MelodieAPIContext.cs
  Melodie.API/Repositories/AlbumRepository.cs
  Melodie.API/Repositories/ArtistRepository.cs
  Melodie.API/Repositories/PlaylistRepository.cs
  Melodie.API/Repositories/SingleRepository.cs
  Melodie.API/Repositories/TrackRepository.cs
  Melodie.API/Repositories/UserRepository.cs
Labels: feature, fix

#42 JWT authorization
  Melodie.API/Controllers/AuthController.cs
  Melodie.API/Data/MelodieAPIContext.cs
  Melodie.API/Dtos/Auth/LoginDto.cs
  Melodie.API/Melodie.API.csproj
  Melodie.API/Program.cs
  Melodie.API/Repositories/AlbumRepository.cs
  Melodie.API/Repositories/ArtistRepository.cs
  Melodie.API/Repositories/BaseRepository.cs
  Melodie.API/Repositories/IBaseRepository.cs
  Melodie.API/Repositories/PlaylistRepository.cs
  Melodie.API/Repositories/Shared/BaseRepository.cs
  Melodie.API/Repositories/Shared/IBaseRepository.cs
  Melodie.API/Repositories/SingleRepository.cs
  Melodie.API/Repositories/TrackRepository.cs
  Melodie.API/Repositories/UserRepository.cs
  Melodie.API/appsettings.json
Labels: feature

#50 Update base repository
  Melodie.API/Repositories/Shared/BaseRepository.cs
  Melodie.API/Repositories/Shared/IBaseRepository.cs
Labels: feature

#54 Reworked seeders
  Melodie.API/Data/DataSeeder.cs
  Melodie.API/Data/Entities/ArtistMusicGenreEntity.cs
  Melodie.API/Data/MelodieAPIContext.cs
  Melodie.API/Migrations/20240730124456_Init.Designer.cs
  Melodie.API/Migrations/20240730124456_Init.cs
  Melodie.API/Migrations/20240731075353_MusicGenreEntity.Designer.cs
  Melodie.API/Migrations/20240731075353_MusicGenreEntity.cs
  Melodie.API/Migrations/20240731080921_UserEntitySeeder.Designer.cs
  Melodie.API/Migrations/20240731080921_UserEntitySeeder.cs
  Melodie.API/Migrations/20240731090504_MusicGenreEntitySeeder.Designer.cs
  Melodie.API/Migrations/20240731090504_MusicGenreEntitySeeder.cs
  Melodie.API/Migrations/20240810140314_EntityRework.Designer.cs
  Melodie.API/Migrations/20240810140314_EntityRework.cs
  Melodie.API/Migrations/20240810142829_TrackManyToMany.Designer.cs
  Melodie.API/Migrations/20240810142829_TrackManyToMany.cs
  Melodie.API/Migrations/20240810174506_ArtistEntitySeeder.Designer.cs
  Melodie.API/Migrations/20240810174506_ArtistEntitySeeder.cs
  Melodie.API/Migrations/20240810175153_MusicGenreEntityRemainingArtists.cs
  Melodie.API/Migrations/20240812195722_Init.Designer.cs
  Melodie.API/Migrations/20240812195722_Init.cs
  Melodie.API/Migrations/MelodieAPIContextModelSnapshot.cs
Labels: feature, fix

#55 Entity rework
  Melodie.API/Data/DataSeeder.cs
  Melodie.API/Data/Entities/AlbumEntity.cs
  Melodie.API/Data/Entities/ArtistEntity.cs
  Melodie.API/Data/Entities/ArtistMusicGenreEntity.cs
  Melodie.API/Data/Entities/LikedEntities/LikedAlbumEntity.cs
  Melodie.API/Data/Entities/LikedEntities/LikedArtistEntity.cs
  Melodie.API/Data/Entities/LikedEntities/LikedSingleEntity.cs
  Melodie.API/Data/Entities/LikedEntities/LikedTrackEntity.cs
  Melodie.API/Data/Entities/PlaylistEntity.cs
  Melodie.API/Data/Entities/QueueEntity.cs
  Melodie.API/Data/Entities/Shared/BaseLikedEntity.cs
  Melodie.API/Data/Entities/Shared/BaseTrackManyToManyEntity.cs
  Melodie.API/Data/Entities/SingleEntity.cs
  Melodie.API/Data/Entities/TrackEntity.cs
  Melodie.API/Data/Entities/TrackManyToManyEntities/AlbumTrackEntity.cs
  Melodie.API/Data/Entities/TrackManyToManyEntities/PlaylistTrackEntity.cs
  Melodie.API/Data/Entities/TrackManyToManyEntities/QueueTrackEntity.cs
  Melodie.API/Data/Entities/TrackManyToManyEntities/SingleTrackEntity.cs
  Melodie.API/Data/Entities/UserEntity.cs
  Melodie.API/Data/MelodieAPIContext.cs
  Melodie.API/Migrations/20240730124456_Init.Designer.cs
  Melodie.API/Migrations/20240730124456_Init.cs
  Melodie.API/Migrations/20240731075353_MusicGenreEntity.Designer.cs
  Melodie.API/Migrations/20240731075353_MusicGenreEntity.cs
  Melodie.API/Migrations/20240731080921_UserEntitySeeder.Designer.cs
  Melodie.API/Migrations/20240731080921_UserEntitySeeder.cs
  Melodie.API/Migrations/20240731090504_MusicGenreEntitySeeder.Designer.cs
  Melodie.API/Migrations/20240731090504_MusicGenreEntitySeeder.cs
  Melodie.API/Migrations/20240810140314_EntityRework.Designer.cs
  Melodie.API/Migrations/20240810140314_EntityRework.cs
  Melodie.API/Migrations/20240810142829_TrackManyToMany.Designer.cs
  Melodie.API/Migrations/20240810142829_TrackManyToMany.cs
  Melodie.API/Migrations/20240810174506_ArtistEntitySeeder.Designer.cs
  Melodie.API/Migrations/20240810174506_ArtistEntitySeeder.cs
  Melodie.API/Migrations/20240810175153_MusicGenreEntityRemainingArtists.cs
  Melodie.API/Migrations/20240812195722_Init.Designer.cs
  Melodie.API/Migrations/20240812195722_Init.cs
  Melodie.API/Migrations/MelodieAPIContextModelSnapshot.cs
  Melodie.API/Repositories/AlbumRepository.cs
  Melodie.API/Repositories/ArtistRepository.cs
  Melodie.API/Repositories/PlaylistRepository.cs
  Melodie.API/Repositories/SingleRepository.cs
  Melodie.API/Repositories/TrackRepository.cs
  Melodie.API/Repositories/UserRepository.cs
Labels: feature, fix

#59 Added singles seeder along with track and singles track seeder
  Melodie.API/Data/DataSeeder.cs
  Melodie.API/Data/Entities/AlbumEntity.cs
  Melodie.API/Data/Entities/QueueEntity.cs
  Melodie.API/Data/Entities/SingleEntity.cs
  Melodie.API/Data/Entities/UserEntity.cs
  Melodie.API/Data/MelodieAPIContext.cs
  Melodie.API/Migrations/20240812195722_Init.Designer.cs
  Melodie.API/Migrations/20240813191454_MusicGenresSeeder.Designer.cs
  Melodie.API/Migrations/20240813191454_MusicGenresSeeder.cs
  Melodie.API/Migrations/20240813192007_ArtistMusicGenresSeeder.cs
  Melodie.API/Migrations/20240813193533_Init.Designer.cs
  Melodie.API/Migrations/20240813193533_Init.cs
  Melodie.API/Migrations/MelodieAPIContextModelSnapshot.cs
Labels: feature

#60 Account registering
  Melodie.API/Controllers/AuthController.cs
  Melodie.API/Dtos/Auth/RegisterDto.cs
Labels: feature

#61 Finished singles seeder
  Melodie.API/Data/DataSeeder.cs
  Melodie.API/Data/Entities/AlbumEntity.cs
  Melodie.API/Data/Entities/SingleEntity.cs
Labels: feature
